name: Build and Deploy Angular App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t phamthanhhung/tradeui:latest -f DockerFile .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push phamthanhhung/tradeui:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to Server and Deploy
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass
        sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${USER}@${{ secrets.VM_HOST }} << 'EOF'
          # Commands to execute on the server
          docker pull phamthanhhung/tradeui:latest
          docker stop tradeapi || true
          docker rm tradeapi || true
          docker run -d -p 8080:8080 --name tradeapi phamthanhhung/tradeui
        EOF
      env:
        USER: root
